name: Main Branch Workflow

on: 
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Maven Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
    - name: Build with Maven
      run: mvn clean package

    - uses: actions/upload-artifact@v3
      with:
        name: verademo.war
        path: target/verademo.war

  policy-scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: get archive
        uses: actions/download-artifact@v3
        with:
          name: verademo.war
          path: .
      - name: Veracoe Upload and Scan Action Step
        uses: veracode/veracode-uploadandscan-action@master
        id: upload_and_scan
        with:
          appname: 'VeraDemo - Web - GitHub'
          createprofile: true
          version: '${{ github.run_id }}'
          filepath: 'verademo.war'
          vid: '${{ secrets.API_ID }}'
          vkey: '${{ secrets.API_KEY}}'
          # scantimeout: 15
        # continue-on-error: true